import type { Metadata } from "next";
import { Courier_Prime, Roboto_Mono } from "next/font/google"; 
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./components/Sidebar_Nav";

const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  subsets: ["latin"],
  weight: ["400", "700"], 
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${courierPrime.variable} ${robotoMono.variable} antialiased lekton-regular `}>
        <ClerkProvider>
          <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <div className="flex-1 w-full">
              <SidebarTrigger className="fixed top-4 right-4 z-40 border-2 border-black bg-white shadow-[2px_2px_0px_rgba(0,0,0,1)] hover:shadow-[4px_4px_0px_rgba(0,0,0,1)] active:translate-y-[2px] active:shadow-none transition-all rounded-none" />
              <main className="w-full h-full">
                {children}
                <Toaster />
              </main>
            </div>
          </SidebarProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
